env:
  dev-release-812
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  redis:
    host: 39.105.153.8
    port: 6379
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://39.105.153.8:3306/springcloud_sell?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=round
  jpa:
    show-sql: true
  rabbitmq:
    host: 39.105.153.8
    port: 5672
    username: guest
    password: guest
