env: dev
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://39.105.153.8:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  jpa:
      show-sql: true
